# -*- coding: utf-8 -*-
"""
/***********************************************************************************************************************
 LandslidesSurvey

 This QGIS plugin allows to retrieve all the data inserted through the smartphone application LandslidesSurvey
 (https://github.com/epessina/LandslidesSurvey). The data can be filtered using a vector layer and downloaded both in
 JSON format and as a Shapefile.
 The plugin is compatible with QGIS 3.x.x and does not require any additional dependency.

 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
 -----------------------------------------------------------------------------------------------------------------------
        begin                : 2019-08-20
        git sha              : $Format:%H$
        copyright            : (C) 2019 by Edoardo Pessina
        email                : edoardo2.pessina@mail.polimi.it
 **********************************************************************************************************************/

/****************************************************************
 *    This program is free software; you can redistribute it    *
 *    and/or modify it under the terms of the GNU GPLv3         *
 *    License https://choosealicense.com/licenses/gpl-3.0/#)    *
 ***************************************************************/
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load LandslidesSurvey class from file LandslidesSurvey.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .landslides_survey import LandslidesSurvey
    return LandslidesSurvey(iface)
